name: clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0+1
  cupertino_icons: ^1.0.2
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_svg: ^0.23.0+1
  injector: ^2.0.0
  localstorage: ^4.0.0+1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.16

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: lib/ui/fonts/SF-Pro-Display-Black.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-BlackItalic.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-Bold.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-BoldItalic.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-Heavy.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-HeavyItalic.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-Light.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-LightItalic.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-Medium.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-MediumItalic.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-Regular.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-RegularItalic.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-Semibold.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-SemiboldItalic.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-Thin.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-ThinItalic.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-Ultralight.ttf
        - asset: lib/ui/fonts/SF-Pro-Display-UltralightItalic.ttf
          style: normal
